### ISSUE TITLE
Add SimpleInjectorAddOptions.ServiceScopeFactory property

### ISSUE THREAD

**Issue by dotnetjunkie** [simpleinjector/SimpleInjector.Integration.AspNetCore#18]
Internally, the `SimpleInjectorAddOptions` class contains a `ServiceScopeFactory` property that pulls in (and caches) the `IServiceScopeFactory` from the root MS.DI container (the `ApplicationServices`). This is used internally to register the `IServiceScope`.

It can be useful to make this property public. This simplifies the Blazor integration, because it needs an alternative way to register `IServiceScope`.

**Comment by dotnetjunkie** [comment]
[feature-18](https://github.com/simpleinjector/SimpleInjector.Integration.AspNetCore/tree/feature-18) branch created.

**Comment by paul-datatech911** [comment]
I looked through the commit related to this issue, and I'm using the latest Simple Injector packages (5.5), but I have some Singleton components that need a `ServiceScopeFactory` injected and Simple Injector is not resolving it.  Do I need to change the `AddOptions` or `UseOptions` somehow?

When I verify the container I get a failure saying that `ServiceScopeFactory` cannot be found, which is what I thought this change fixed.

``` c#
Container container = new Container();
builder.Services.AddSimpleInjector(container, options =>
{	
});

var host = builder.Build();
host.UseSimpleInjector(container);
// ... Register Services in Container
container.Verify();
```

<img width="1022" alt="Image" src="https://github.com/user-attachments/assets/8a383c2a-880c-45a7-a659-cc3c5ab196b9" />

**Comment by dotnetjunkie** [comment]
The thing is that MS.DI's `IServiceScopeFactory` is never made part of the `ServiceCollection`. It's one of the few registrations that are added implicitly when the container is built. Simple Injector's ASP.NET Core integration, however, makes use of the list of registrations in `ServiceCollection` to find out which registrations are there to allow dependencies to be cross-wired from MS.DI to Simple Injector. But since `IServiceScopeFactory` is not in the list, that dependency can't be automatically cross-wired.

The solution is to cross-wire it manually in Simple Injector:

``` c#
    .AddSimpleInjector(container, options =>
    {
        options.CrossWire<IServiceScopeFactory>();
    })
```

**Comment by paul-datatech911** [comment]
That partially worked - thanks!  

The problem I'm trying to solve is the classic non-Singleton Service from a Singleton service.  Unfortunately it looks like manually calling Crosswire<T>() registers the T as a Transient Service with no overloads to control lifetime.  In this case I want the IServiceScopeFactory specifically so I can create a scoped service from within a singleton.  I think MS.DI wires up IISF as a singleton for this purpose, but in SimpleInjector I get the LifestyleMismatch error : 

> SimpleInjector.DiagnosticVerificationException: 'The configuration is invalid. The following diagnostic warnings were reported:
> -[Lifestyle Mismatch] ServiceBusTopicNotifier2 (Singleton) depends on IServiceScopeFactory (Transient).
> See the Error property for detailed information about the warnings. Please see https://simpleinjector.org/diagnostics how to fix problems and how to suppress individual warnings.'

**Comment by dotnetjunkie** [comment]
Let's take a step back. Why are you injecting `IServiceScopeFactory` in the first place, rather than injecting the Simple Injector Container? Your `ServiceBusTopicNotifier2` is a Simple Injector-registered component, so why not create new Simple Injector `Scope` instances from within `ServiceBusTopicNotifier2`?

**Comment by paul-datatech911** [comment]
Was following guidance related to Microsoft's Background Worker (& my related classes) being registered as a singleton by default.  ServiceBusTopicNotifier is a class I use in BackgroundWorker, but I also use in a difference process that gets services by SimpleInjector.  I was trying to get both to play nice together.
