### ISSUE TITLE
Best practices for writing Integration Tests with WebApplicationFactory

### ISSUE THREAD

**Issue by Ergamon** [simpleinjector/SimpleInjector.Integration.AspNetCore#21]
I am missing some guidance to setup AspNetCore integration tests while using SimpleInjector.

I setup my project like described here https://docs.simpleinjector.org/en/latest/aspnetintegration.html

I am using some simple code to replace some of the Microsoft registrations.

A simplified version looks like this:

```
public class WebApplicationFixture : WebApplicationFactory<Startup>
{
  protected override void ConfigureWebHost(IWebHostBuilder builder)
  {
     builder .ConfigureServices(ConfigureServices);
  }

  private void ConfigureServices(IServiceCollection services)
  {
     //  ...
  }
}
```

So far, so much copied from the MS documentation.

Now my only real problem is to get a reference to my SimpleInjector container. The easiest approach I would have preferred is to have some kind of factory for the Startup class, but either I am blind or MS does not provide any way to achieve this with the WebApplicationFactory.

As I cannot get any reference to the Startup instance, there is no point in making the container a public property.

So far I found 2 solutions:
Create a special inherited version of the Startup class. By making the InitializeContainer method protected virtual I can add functionality there. But having the Startup class in the integration test project adds a lot of stuff to add just for loading resources and controllers from the right assembly.

My other approach is to register the container as a singleton and writing my ConfigureServices like this:
```
  private void ConfigureServices(IServiceCollection services)
  {
     // override MS registrations
     
     var serviceProvider = services.BuildServiceProvider();
     var container = serviceProvider.GetService<Container>();
     container.Options.AllowOverridingRegistrations = true;
     // override SimpleInjector registrations
   }
```

Is there any recommended way to do this?

**Comment by dotnetjunkie** [comment]
I have no experience with `WebApplicationFactory` whatsoever, but to get the container, you might be able to do this as well:

``` c#
  private void ConfigureServices(IServiceCollection services)
  {
     // override MS registrations

    var container = (Container)services.Last(d => d.ServiceType == typeof(Container)).ImplementationInstance;
     
     container.Options.AllowOverridingRegistrations = true;
     // override Simple Injector registrations
   }
```

When calling `services.AddSimpleInjector()`, Simple Injector adds itself to the `IServiceCollection`, which is why you should be able to iterate the `IServiceCollection` to find the `Container` instance. There should be no need to build the `IServiceCollection`.

**Comment by Ergamon** [comment]
Basically WebApplicationFactory is a class provided by MS for doing integration testing. Just by providing the Startup class you can create a IHttpClient instance doing all  the stuff necessary in the background.

It works fantastic, if you can use the production code 1:1 in your test environment.

For exensibility to mock some services they offer this ConfigureServices extension point. Of course there is no example for working with SimpleInjector ;)

I modified my code according to the code you provided and it works like a charm. It looks way cleaner without the extra step of producing a temporary service provider.

Thx for your help
